# 语言, 默认为英文en-us, 中文为zh-cn
language: en-us

# ceye.io的域名和token
ceye-domain: Null
ceye-token: Null

# dnslog.pw的域名和token
# 默认带有试用域名和Token, 会过期, 可以替换为自己的
dnslog-pw-domain: im4v3kv9.dnslog.pw
dnslog-pw-token: 1221dd92

# 请求Header
  # 运行时指定--user-agent参数, 会覆盖config.yaml的User-Agent
headers:
  User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
  Content-Type: "application/x-www-form-urlencoded"
  Accept: "*/*"
  Connection: "close"

payloads-path: ./payloads/
